/**
 * Appuntamenti versione 1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailConfiguration } from './emailConfiguration';


export interface ApplicationConfiguration {
    applicationName?: string;
    maxListItems?: number;
    emailSettings?: EmailConfiguration;
}
